name: Hello World workflow
on:
  # workflow_dispatch option enables manual trigger button
  workflow_dispatch:

# under job key we define the names and jobs definitions, typically as multiple steps
# e.g. what commands to run, what environment to set
jobs:
  # our job name: `hello-world-job`
  hello-world-job:
    # our job definition
    runs-on: ubuntu-latest # here, define image on which we will run our job
    
    # definitions of all job steps
    steps:
      - name: Print Hello World # step name, displayed on UI
        run: echo "Hello world!" # print "Hello world!" here

# github context
name: Github context example
on: workflow_dispatch
jobs:
  show-github-context:
    runs-on: ubuntu-latest
    steps:
       - name: Github Context
         run: | # "|" is a new line in YAML, useful for readable multiline commands
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"