# secrets context
# secrets are repository-level variables that should be encrypted
# and can be reused in many individual workflows

name: Secrets Context Example

on: workflow_dispatch

jobs:
   show-secrets:
      runs-on: ubuntu-latest
      steps:
         - name: Use a secret (masked in logs)
           run: |
            echo "API Key: ${{ secrets.API_KEY }}"